name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # ou la branche que tu veux surveiller

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kush43/chat-php:latest
